stuff: folder
	touch nice_folder/nice_textfile.txt
	touch nice_folder/nice_csv_file.csv
	touch nice_folder/nice_markdown.md
	touch nice_folder/nice_config.config


folder:
	mkdir nice_folder


remove:
	rm -r nice_folder