nice_file:
	echo "This line will always print, because nice_file will never be created"


cool_file:
	echo "This message is only shown if cool_file doesn't exist yet"
	touch cool_file


remove:
	rm -f cool_file